"""
Script: /src/scripts/tree_http_analysis.py

Author: Anya Barringer, aided by Claude Sonnet 4.6 and
        Codestral through Furman University BoodleBox

Container:  Part of CSC Summer Research 2026 Project
            "Pervasive Online Third-Party Tracking: A Measurement Study"
            with Graham Fink, under Dr. Rebecca Drucker

Goal:   Classifies http requests as first- vs third-party.
        Http requests are found in http_requests table in
        .sqlite file output by OpenWPM from browser crawl.
        Loads output_tree.csv generated by build_mapping_tree.py
        for hierarchical relationship classification reference.
        Outputs three data analysis summary .csv files for 
        requests made, visits made, and trackers identified.
"""



import os
import json
import logging
import sqlite3
import pandas as pd
from collections import defaultdict
from types import SimpleNamespace
from bigtree import Node, Tree, dataframe_to_tree
from src.utilities.utils import get_registered_domain, get_node_info, load_tree, classify_relationship


# --- CONSTANTS ---
from config import (
    DB_PATH,
    TREE_OUTPUT_CSV,
    OUTPUT_REQUESTS_CSV,
    OUTPUT_SUMMARIES_CSV,
    OUTPUT_TRACKERS_CSV
)

# --- LOGGING SETUP ---
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s — %(name)s — %(levelname)s — %(message)s"
)
logger = logging.getLogger(__name__)



# =============================================================================
# (1) DATA LOADING
# =============================================================================
def load_data() -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    """
    Connects to SQLite database and loads all necessary DataFrames
    and lookup structures for classification pipeline.

    Returns:
        site_visits_df  : DataFrame of all site visits (visit_id, site_url)
        http_requests_df: DataFrame of all HTTP requests
        incomplete_map  : dict {visit_id: timeout_command} for incomplete visits
    """
    conn = sqlite3.connect(DB_PATH)

    # --- site_visits: anchor for the outer loop ---
    site_visits_df = pd.read_sql_query(
        "SELECT visit_id, site_url FROM site_visits", conn
    )

    # --- incomplete_visits + crawl_history join ---
    # For each incomplete visit_id, find the LAST command recorded in
    # crawl_history using SQLite's implicit rowid as an ordering key.
    # That command is the one that timed out.
    incomplete_query = """
        SELECT
            iv.visit_id,
            ch.command AS timeout_command
        FROM incomplete_visits iv
        LEFT JOIN crawl_history ch
            ON iv.visit_id = ch.visit_id
        WHERE ch.rowid = (
            SELECT MAX(ch2.rowid)
            FROM crawl_history ch2
            WHERE ch2.visit_id = iv.visit_id
        )
    """
    incomplete_df  = pd.read_sql_query(incomplete_query, conn)

    # Build a lookup dict where {visit_id: timeout_command_string}
    incomplete_map = dict(
        zip(incomplete_df['visit_id'], incomplete_df['timeout_command'])
    )

    # --- http_requests: data for the inner classification loop ---
    requests_query = """
        SELECT
            visit_id,
            request_id,
            url,
            top_level_url,
            resource_type,
            referrer
        FROM http_requests
    """
    http_requests_df = pd.read_sql_query(requests_query, conn)
    conn.close()

    logger.info(f"Incomplete visits found: {len(incomplete_map)}")
    logger.info(f"Breakdown: {pd.Series(incomplete_map).value_counts().to_dict()}")
    logger.info(f"Loaded {len(site_visits_df)} site visits.")
    logger.info(f"Loaded {len(http_requests_df)} HTTP requests.")

    return site_visits_df, http_requests_df, incomplete_map


# =============================================================================
# (2) CLASSIFICATION LOOP
# =============================================================================
def classify_requests(
        site_visits_df: pd.DataFrame,
        http_requests_df: pd.DataFrame,
        incomplete_map: dict,
        domain_to_node: dict
    ) -> tuple[list, list, dict, dict]:
    """
    Iterates over every site visit and every HTTP request within it,
    classifying each request using two-level parent/subsidiary hierarchy:

        first-party:              parent == top_parent AND subsidiary == top_subsidiary
        inter-family third-party: parent == top_parent AND subsidiary != top_subsidiary
        external third-party:     parent != top_parent (subsidiary irrelevant)
        unknown:                  domain unresolvable via get_registered_domain()

    Also records is_technical_3p — whether request domain differs from
    top-level domain at raw eTLD+1 level, regardless of entity classification.

    Classification logic is delegated to classify_relationship(), which handles
    both entity attribute access and unknown domain pass-through fallback.

    Args:
        site_visits_df  : DataFrame from load_data()
        http_requests_df: DataFrame from load_data()
        incomplete_map  : dict from load_data()
        domain_to_node  : dict from load_tree()

    Returns:
        all_requests_rows : list of dicts — one per HTTP request
        visit_summary_rows: list of dicts — one per site visit
        tracker_prevalence: defaultdict(set) — {third-party domain: {(visit_id, top_domain), ...}}
        first_party_coverage: defaultdict(int) — {first-party domain: visit_count}
    """

    tracker_prevalence   = defaultdict(set)
    first_party_coverage = defaultdict(int)
    all_requests_rows    = []
    visit_summary_rows   = []

    # OUTER LOOP — one iteration per site visit
    for _, visit in site_visits_df.iterrows():
        v_id            = visit['visit_id']
        site_url        = visit['site_url']
        timeout_command = incomplete_map.get(v_id, None)
        visit_complete  = 0 if timeout_command is not None else 1

        visit_requests   = http_requests_df[http_requests_df['visit_id'] == v_id].copy()
        visit_top_domain = get_registered_domain(site_url)

        if visit_top_domain:
            first_party_coverage[visit_top_domain] += 1

        counts = {
            "first-party": 0,
            "inter-family third-party": 0,
            "external third-party": 0,
            "unknown": 0
        }
        visit_third_party_domains = set()

        # INNER LOOP — one iteration per HTTP request within this visit
        for _, req in visit_requests.iterrows():
            req_url        = req['url']
            req_domain     = get_registered_domain(req_url)
            req_top_domain = get_registered_domain(req['top_level_url']) or visit_top_domain

            # Top-level and request node lookups
            # Pass-through fallback handled in get_node_info()
            top_node = get_node_info(req_top_domain, domain_to_node)
            req_node = get_node_info(req_domain, domain_to_node)

            # Unknown domain guard - skip classification if unresolvable
            if not req_domain or not req_top_domain:
                classification   = "unknown"
                is_tp_val        = None
                is_technical_3p  = None
                req_sub          = None
                req_parent       = None
                counts["unknown"] += 1

            else:
                # Attribute extraction — fallback to eTLD+1 string if node not in tree
                req_sub    = req_node.subsidiary_entity
                req_parent = req_node.parent_entity
                
                # Technical 3P check by raw eTLD+1 comparison, statistic + gate before entity lookup
                is_technical_3p = int(req_domain != req_top_domain)

                # Two-level hierarchy classification
                if is_technical_3p == 0:
                    # Domains identical — must be first-party, no tree lookup needed
                    classification = "first-party"
                    is_tp_val      = 0
                    counts["first-party"] += 1

                else:
                    # Domains differ — delegate to entity-aware classification
                    result = classify_relationship(req_node, top_node)

                    if result["is_parent_third_party"]:
                        # Different parent and subsidiary entities
                        classification = "external third-party"
                        is_tp_val      = 1
                        counts["external third-party"] += 1
                        tracker_prevalence[req_domain].add((v_id, req_top_domain))
                        visit_third_party_domains.add(req_domain)

                    elif result["is_subsidiary_third_party"]:
                        # Different subsidiary but same parent entities
                        classification = "inter-family third-party"
                        is_tp_val      = 1
                        counts["inter-family third-party"] += 1
                        tracker_prevalence[req_domain].add((v_id, req_top_domain))
                        visit_third_party_domains.add(req_domain)

                    else:
                        # Domains differ but entity resolves to same parent — first-party
                        classification = "first-party"
                        is_tp_val      = 0
                        counts["first-party"] += 1

            # Append stats row for each request
            all_requests_rows.append({
                'visit_id':              v_id,
                'request_id':            req['request_id'],
                'url':                   req_url,
                'request_domain':        req_domain,
                'request_subsidiary':    req_sub,
                'request_parent':        req_parent,
                'top_level_domain':      req_top_domain,
                'is_technical_3p':       is_technical_3p,
                'is_third_party':        is_tp_val,
                'classification':        classification,
                'resource_type':         req['resource_type'],
                'referrer':              req['referrer'],
                'visit_complete':        visit_complete,
            })

        # END INNER LOOP
        # Append summary row after all requests per visit are processed
        visit_summary_rows.append({
            'visit_id':                v_id,
            'site_url':                site_url,
            'visit_complete':          visit_complete,
            'timeout_command':         timeout_command,
            'total_requests':          len(visit_requests),
            'first_party_count':       counts["first-party"],
            'inter_family_tp_count':   counts["inter-family third-party"],
            'external_tp_count':       counts["external third-party"],
            'unknown_count':           counts["unknown"],
            'third_party_domains':     ", ".join(sorted(visit_third_party_domains))
        })

    logger.info(f"Classified {len(all_requests_rows)} total requests from {len(visit_summary_rows)} total visits.")
    
    return all_requests_rows, visit_summary_rows, tracker_prevalence, first_party_coverage


# =============================================================================
# (3) EXPORT LOGIC
# =============================================================================
def export_requests(all_requests_rows: list, export_path: str):
    """
    Exports granular HTTP request rows to CSV.
    One row per request with classification, entity, and technical metadata.

    Args:
        all_requests_rows: List of dicts from classify_requests()
        export_path:       Output CSV path
    """
    df = pd.DataFrame(all_requests_rows)
    df.to_csv(export_path, index=False)
    logger.info(f"Requests written:  {len(df)} rows → {export_path}")

def export_visit_summaries(visit_summary_rows: list, export_path: str):
    """
    Exports per-visit summary statistics to CSV.
    One row per site visit with aggregate counts per classification tier.

    Args:
        visit_summary_rows: List of dicts from classify_requests()
        export_path:        Output CSV path
    """
    df = pd.DataFrame(visit_summary_rows)
    df.to_csv(export_path, index=False)
    logger.info(f"Summaries written: {len(df)} rows → {export_path}")

def export_tracker_prevalence(tracker_prevalence: dict, export_path: str):
    """
    Aggregates tracker_prevalence into reach and volume statistics
    per third-party domain and exports to CSV.
        site_count  — reach:  number of unique sites on which this domain appeared
        visit_count — volume: number of unique visits in which this domain appeared

    Args:
        tracker_prevalence: defaultdict(set) from classify_requests()
        export_path:        Output CSV path
    """
    tracker_stats = []
    for domain, occurrences in tracker_prevalence.items():
        unique_sites = sorted({site for vid, site in occurrences if site})
        unique_vids  = sorted({vid  for vid, site in occurrences})

        tracker_stats.append({
            'third_party_domain': domain,
            'site_count':         len(unique_sites),
            'visit_count':        len(unique_vids),
            'sites_visited':      ", ".join(unique_sites),
            'visit_ids':          ", ".join(map(str, unique_vids))
        })

    tracker_df = pd.DataFrame(tracker_stats)
    if not tracker_df.empty:
        tracker_df = tracker_df.sort_values(by='site_count', ascending=False)

    tracker_df.to_csv(export_path, index=False)
    logger.info(f"Trackers written:  {len(tracker_df)} unique domains → {export_path}")

def export_results(all_requests_rows: list, visit_summary_rows: list, tracker_prevalence: dict):
    """
    Wrapper that triggers all three export helpers in sequence.

    Args:
        all_requests_rows : list of dicts from classify_requests()
        visit_summary_rows: list of dicts from classify_requests()
        tracker_prevalence: defaultdict(set) from classify_requests()
    """
    export_requests(all_requests_rows, OUTPUT_REQUESTS_CSV)
    export_visit_summaries(visit_summary_rows, OUTPUT_SUMMARIES_CSV)
    export_tracker_prevalence(tracker_prevalence, OUTPUT_TRACKERS_CSV)


# =============================================================================
# MAIN EXECUTION BLOCK
# =============================================================================
def main():
    logger.info("=== Starting HTTP Request Classification Pipeline ===")
    
    # Step 1: Load resources
    logger.info("--- Step 1: Loading Data and Entity Tree ---")
    site_visits_df, http_requests_df, incomplete_map = load_data()
    root, domain_to_node = load_tree(TREE_OUTPUT_CSV)
    
    # Step 2: Classify requests
    logger.info("--- Step 2: Classifying Requests ---")
    all_reqs, visit_sums, trackers, _ = classify_requests(
        site_visits_df, http_requests_df, incomplete_map, domain_to_node
    )
    
    # Step 3: Export results
    logger.info("--- Step 3: Exporting Results ---")
    export_results(all_reqs, visit_sums, trackers)
    logger.info(f"Files generated: {OUTPUT_REQUESTS_CSV}, {OUTPUT_SUMMARIES_CSV}, {OUTPUT_TRACKERS_CSV}")
    
    logger.info("=== Pipeline Execution Complete ===")

if __name__ == "__main__":
    main()